Repository Dsm-DAS/DAS_BACKEND, pull requests merged in 2022-09, with the labels that each got.

#2 🔀 :: (#1) CODEOWNERS 세팅
  .github/CODEOWNERS
Labels: 프로젝트 세팅

#4 🔀 :: (#3) yml 파일 생성
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: 프로젝트 세팅

#6 🔀 :: (#5) 파일 구조 세팅
  build.gradle
  src/main/java/com/das/das_backend/domain/admin/.gitkeep
  src/main/java/com/das/das_backend/domain/comment/.gitkeep
  src/main/java/com/das/das_backend/domain/feed/.gitkeep
  src/main/java/com/das/das_backend/domain/manager/.gitkeep
  src/main/java/com/das/das_backend/domain/notice/.gitkeep
  src/main/java/com/das/das_backend/domain/teacher/.gitkeep
  src/main/java/com/das/das_backend/domain/user/.gitkeep
  src/main/java/com/das/das_backend/global/.gitkeep
Labels: 프로젝트 세팅

#8 🔀 :: (#7) User 엔티티 생성
  src/main/java/com/das/das_backend/domain/user/domain/User.java
  src/main/java/com/das/das_backend/infrastructure/s3/DefaultImage.java
Labels: 기능 추가

#11 🔀 :: (#10) 권한 컬럼 추가
  src/main/java/com/das/das_backend/domain/user/.gitkeep
  src/main/java/com/das/das_backend/domain/user/domain/User.java
  src/main/java/com/das/das_backend/global/.gitkeep
  src/main/java/com/das/das_backend/global/enums/Authority.java
Labels: 기능 수정

#13 🔀 :: (#12) Feed 엔티티 생성
  src/main/java/com/das/das_backend/domain/feed/domain/Feed.java
  src/main/java/com/das/das_backend/domain/user/domain/User.java
Labels: 기능 추가

#17 🔀 :: (#16) like 엔티티 생성
  src/main/java/com/das/das_backend/domain/like/domain/Like.java
Labels: 기능 추가

#19 🔀 :: (#18) 엔티티 기본키 버그 수정
  src/main/java/com/das/das_backend/domain/comment/domain/Comment.java
  src/main/java/com/das/das_backend/domain/feed/domain/Feed.java
  src/main/java/com/das/das_backend/domain/user/domain/User.java
  src/main/java/com/das/das_backend/global/entity/BaseIdEntity.java
  src/main/java/com/das/das_backend/global/entity/BaseTimeIdEntity.java
Labels: 기능 수정

#21 🔀 :: (#20) Notice 엔티티 생성
  src/main/java/com/das/das_backend/domain/notice/.gitkeep
  src/main/java/com/das/das_backend/domain/notice/Notice.java
Labels: 기능 추가

#23 🔀 :: (#22) 예외처리 추가
  src/main/java/com/das/das_backend/global/error/DasException.java
  src/main/java/com/das/das_backend/global/error/ErrorCode.java
  src/main/java/com/das/das_backend/global/error/ErrorResponse.java
  src/main/java/com/das/das_backend/global/error/ExceptionFilter.java
  src/main/java/com/das/das_backend/global/error/GlobalExceptionHandler.java
Labels: 기능 추가

#25 🔀 :: (#24) security setting
  src/main/java/com/das/das_backend/domain/user/domain/repository/UserRepository.java
  src/main/java/com/das/das_backend/domain/user/exception/UserNotFoundException.java
  src/main/java/com/das/das_backend/global/error/ErrorCode.java
  src/main/java/com/das/das_backend/global/security/SecurityConfig.java
  src/main/java/com/das/das_backend/global/security/auth/AuthDetails.java
  src/main/java/com/das/das_backend/global/security/auth/AuthDetailsService.java
Labels: 기능 추가

#27 🔀 :: (#26) jwt setting
  src/main/java/com/das/das_backend/DasBackendApplication.java
  src/main/java/com/das/das_backend/domain/auth/domain/RefreshToken.java
  src/main/java/com/das/das_backend/domain/auth/domain/repository/RefreshTokenRepository.java
  src/main/java/com/das/das_backend/global/error/ErrorCode.java
  src/main/java/com/das/das_backend/global/exception/ExpiredTokenException.java
  src/main/java/com/das/das_backend/global/exception/InvalidTokenException.java
  src/main/java/com/das/das_backend/global/redis/RedisConfig.java
  src/main/java/com/das/das_backend/global/security/jwt/JwtProperties.java
  src/main/java/com/das/das_backend/global/security/jwt/JwtTokenFilter.java
  src/main/java/com/das/das_backend/global/security/jwt/JwtTokenProvider.java
Labels: 기능 추가

#31 🔀 :: (#29) 로그인 api
  src/main/java/com/das/das_backend/domain/refresh_token/domain/RefreshToken.java
  src/main/java/com/das/das_backend/domain/refresh_token/domain/repository/RefreshTokenRepository.java
  src/main/java/com/das/das_backend/domain/user/exception/PasswordMisMatchException.java
  src/main/java/com/das/das_backend/domain/user/presentation/UserController.java
  src/main/java/com/das/das_backend/domain/user/presentation/dto/request/UserSignInRequest.java
  src/main/java/com/das/das_backend/domain/user/presentation/dto/response/TokenResponse.java
  src/main/java/com/das/das_backend/domain/user/service/UserSignInService.java
  src/main/java/com/das/das_backend/global/error/ErrorCode.java
  src/main/java/com/das/das_backend/global/security/jwt/JwtTokenProvider.java
Labels: 기능 추가

#30 🔀 :: (#28) 유저 회원가입 api
  src/main/java/com/das/das_backend/domain/user/exception/UserAlreadyExistsException.java
  src/main/java/com/das/das_backend/domain/user/presentation/UserController2.java
  src/main/java/com/das/das_backend/domain/user/presentation/dto/request/UserSignUpRequest.java
  src/main/java/com/das/das_backend/domain/user/service/UserSignUpService.java
  src/main/java/com/das/das_backend/global/error/ErrorCode.java
  src/main/java/com/das/das_backend/global/security/SecurityConfig.java
  src/main/java/com/das/das_backend/infrastructure/s3/DefaultImage.java
Labels: 기능 추가

#34 🔀 :: (#33) Conflict 버그 수정
  src/main/java/com/das/das_backend/domain/user/presentation/UserController.java
  src/main/java/com/das/das_backend/domain/user/presentation/UserController2.java
  src/main/java/com/das/das_backend/global/error/ErrorCode.java
Labels: 버그

#36 🔀 :: (#35) accountId + email -> email로 수정
  src/main/java/com/das/das_backend/domain/refresh_token/domain/RefreshToken.java
  src/main/java/com/das/das_backend/domain/user/domain/User.java
  src/main/java/com/das/das_backend/domain/user/domain/repository/UserRepository.java
  src/main/java/com/das/das_backend/domain/user/facade/UserFacade.java
  src/main/java/com/das/das_backend/domain/user/presentation/dto/request/UserSignInRequest.java
  src/main/java/com/das/das_backend/domain/user/presentation/dto/request/UserSignUpRequest.java
  src/main/java/com/das/das_backend/domain/user/service/UserSignInService.java
  src/main/java/com/das/das_backend/domain/user/service/UserSignUpService.java
  src/main/java/com/das/das_backend/global/security/SecurityConfig.java
Labels: 버그, 기능 수정

#40 🔀:: (#38) 회원탈퇴 api
  src/main/java/com/das/das_backend/domain/user/presentation/UserController.java
  src/main/java/com/das/das_backend/domain/user/service/UserWithdrawalService.java
  src/main/java/com/das/das_backend/global/security/SecurityConfig.java
Labels: 기능 추가

#43 🔀 :: (#39) 비밀번호 수정 API
  src/main/java/com/das/das_backend/domain/user/domain/User.java
  src/main/java/com/das/das_backend/domain/user/presentation/UserController.java
  src/main/java/com/das/das_backend/domain/user/presentation/dto/request/ChangePasswordRequest.java
  src/main/java/com/das/das_backend/domain/user/service/ChangePasswordService.java
Labels: 기능 추가

#45 🔀 :: (#44) 모집글 작성 API
  src/main/java/com/das/das_backend/domain/feed/domain/repository/FeedRepository.java
  src/main/java/com/das/das_backend/domain/feed/presentation/FeedController.java
  src/main/java/com/das/das_backend/domain/feed/presentation/dto/request/CreateFeedRequest.java
  src/main/java/com/das/das_backend/domain/feed/service/CreateFeedService.java
Labels: 기능 추가

#42 🔀 :: (#41) 토큰 재발급 API
  src/main/java/com/das/das_backend/domain/like/domain/Like.java
  src/main/java/com/das/das_backend/domain/refresh_token/domain/RefreshToken.java
  src/main/java/com/das/das_backend/domain/refresh_token/domain/repository/RefreshTokenRepository.java
  src/main/java/com/das/das_backend/domain/user/exception/InvalidRefreshTokenException.java
  src/main/java/com/das/das_backend/domain/user/presentation/UserController.java
  src/main/java/com/das/das_backend/domain/user/service/TokenRefreshService.java
  src/main/java/com/das/das_backend/global/error/ErrorCode.java
  src/main/java/com/das/das_backend/global/security/auth/AuthDetails.java
  src/main/java/com/das/das_backend/global/security/auth/AuthDetailsService.java
  src/main/java/com/das/das_backend/global/security/jwt/JwtTokenProvider.java
Labels: 기능 추가

#50 🔀 :: (#47) 모집글 수정 API
  src/main/java/com/das/das_backend/domain/feed/domain/Feed.java
  src/main/java/com/das/das_backend/domain/feed/exception/FeedCannotUpdateException.java
  src/main/java/com/das/das_backend/domain/feed/exception/FeedNotFoundException.java
  src/main/java/com/das/das_backend/domain/feed/facade/FeedFacade.java
  src/main/java/com/das/das_backend/domain/feed/presentation/FeedController.java
  src/main/java/com/das/das_backend/domain/feed/presentation/dto/request/UpdateFeedRequest.java
  src/main/java/com/das/das_backend/domain/feed/service/UpdateFeedService.java
  src/main/java/com/das/das_backend/global/error/ErrorCode.java
Labels: 기능 추가

#49 🔀 :: (#48) 공지 사항 작성 API
  src/main/java/com/das/das_backend/domain/notice/domain/Notice.java
  src/main/java/com/das/das_backend/domain/notice/domain/repository/NoticeRepository.java
  src/main/java/com/das/das_backend/domain/notice/presentation/NoticeController.java
  src/main/java/com/das/das_backend/domain/notice/presentation/dto/request/CreateNoticeRequest.java
  src/main/java/com/das/das_backend/domain/notice/service/CreateNoticeService.java
  src/main/java/com/das/das_backend/global/security/SecurityConfig.java
Labels: 기능 추가

#59 🔀 :: (#58) 댓글 삭제 API
  src/main/java/com/das/das_backend/domain/comment/service/DeleteCommentService.java
Labels: 기능 추가

#57 🔀 :: (#56) 댓글 수정 API
  src/main/java/com/das/das_backend/domain/comment/presentation/dto/request/UpdateCommentRequest.java
  src/main/java/com/das/das_backend/domain/comment/service/UpdateCommentService.java
Labels: 기능 추가

#55 🔀 :: (#54) 댓글 작성 API
  src/main/java/com/das/das_backend/domain/comment/domain/Comment.java
  src/main/java/com/das/das_backend/domain/comment/domain/repository/CommentRepository.java
  src/main/java/com/das/das_backend/domain/comment/exception/CommentCannotDeleteException.java
  src/main/java/com/das/das_backend/domain/comment/exception/CommentCannotUpdateException.java
  src/main/java/com/das/das_backend/domain/comment/exception/CommentNotFoundException.java
  src/main/java/com/das/das_backend/domain/comment/facade/CommentFacade.java
  src/main/java/com/das/das_backend/domain/comment/presentation/CommentController.java
  src/main/java/com/das/das_backend/domain/comment/presentation/dto/request/CreateCommentRequest.java
  src/main/java/com/das/das_backend/domain/comment/service/CreateCommentService.java
  src/main/java/com/das/das_backend/global/error/ErrorCode.java
Labels: 기능 추가

#62 🔀 :: (#61) CORS 버그
  src/main/java/com/das/das_backend/global/web/WebMvcConfig.java
Labels: 버그

#60 🔀 :: (#46) Email 인증 API
  build.gradle
  src/main/java/com/das/das_backend/domain/user/domain/AuthCode.java
  src/main/java/com/das/das_backend/domain/user/domain/repository/AuthCodeRepository.java
  src/main/java/com/das/das_backend/domain/user/exception/InvalidAuthCodeException.java
  src/main/java/com/das/das_backend/domain/user/exception/UnVerifiedAuthCodeException.java
  src/main/java/com/das/das_backend/domain/user/exception/WrongEmailException.java
  src/main/java/com/das/das_backend/domain/user/facade/AuthCodeFacade.java
  src/main/java/com/das/das_backend/domain/user/facade/UserFacade.java
  src/main/java/com/das/das_backend/domain/user/presentation/UserController.java
  src/main/java/com/das/das_backend/domain/user/presentation/dto/request/EmailRequest.java
  src/main/java/com/das/das_backend/domain/user/presentation/dto/request/VerifyAuthCodeRequest.java
  src/main/java/com/das/das_backend/domain/user/service/AuthCodeService.java
  src/main/java/com/das/das_backend/domain/user/service/UserSignUpService.java
  src/main/java/com/das/das_backend/domain/user/service/VerifyAuthCodeService.java
  src/main/java/com/das/das_backend/global/error/ErrorCode.java
  src/main/java/com/das/das_backend/global/security/FilterConfig.java
  src/main/java/com/das/das_backend/global/security/SecurityConfig.java
  src/main/java/com/das/das_backend/global/util/JmsUtil.java
  src/main/resources/application.yml
Labels: 기능 추가

#64 🔀 :: (#63) updateCommentService 수정
  src/main/java/com/das/das_backend/domain/comment/service/UpdateCommentService.java
Labels: 버그

#67 🔀 :: (#66) 회원가입 버그 수정
  src/main/java/com/das/das_backend/domain/user/domain/User.java
Labels: 버그

#69 🔀 :: (#68) SecurityConfig url 접근 권한 추가
  src/main/java/com/das/das_backend/domain/comment/presentation/CommentController.java
  src/main/java/com/das/das_backend/global/security/SecurityConfig.java
Labels: 기능 추가

#73 🔀 :: (#72) CI 세팅
  .github/workflows/CI.yml
  src/test/java/com/das/das_backend/DasBackendApplicationTests.java
Labels: 프로젝트 세팅

#74 🔀 :: (#70) S3 setting
  build.gradle
  src/main/java/com/das/das_backend/domain/image/presentation/ImageController.java
  src/main/java/com/das/das_backend/domain/image/presentation/dto/response/ImageUrlResponse.java
  src/main/java/com/das/das_backend/domain/image/service/ImageUploadService.java
  src/main/java/com/das/das_backend/global/error/ErrorCode.java
  src/main/java/com/das/das_backend/global/exception/ImageValueNotFoundException.java
  src/main/java/com/das/das_backend/global/exception/SaveImageFailedException.java
  src/main/java/com/das/das_backend/infrastructure/s3/S3Facade.java
  src/main/java/com/das/das_backend/infrastructure/s3/S3Properties.java
  src/main/resources/application.yml
Labels: 기능 추가

#76 🔀 :: (#71) 소켓 setting
  build.gradle
  src/main/java/com/das/das_backend/DasBackendApplication.java
  src/main/java/com/das/das_backend/global/socket/SocketRunner.java
  src/main/java/com/das/das_backend/global/socket/WebSocketConfig.java
  src/main/java/com/das/das_backend/global/socket/connect/SocketJwtHandler.java
  src/main/java/com/das/das_backend/global/socket/exception/SocketExceptionListener.java
  src/main/java/com/das/das_backend/global/socket/property/ClientProperty.java
  src/main/java/com/das/das_backend/global/socket/property/SocketProperty.java
  src/main/resources/application.yml
Labels: 기능 추가

#78 🔀 :: (#77) 모집글 좋아요 API
  src/main/java/com/das/das_backend/domain/feed/domain/Feed.java
  src/main/java/com/das/das_backend/domain/like/domain/repository/LikeRepository.java
  src/main/java/com/das/das_backend/domain/like/exception/LikeExistException.java
  src/main/java/com/das/das_backend/domain/like/exception/RemoveLikeExistException.java
  src/main/java/com/das/das_backend/domain/like/facade/LikeFacade.java
  src/main/java/com/das/das_backend/domain/like/presentation/LikeController.java
  src/main/java/com/das/das_backend/domain/like/presentation/dto/response/LikeResponse.java
  src/main/java/com/das/das_backend/domain/like/service/LikeService.java
  src/main/java/com/das/das_backend/global/error/ErrorCode.java
Labels: 기능 추가
