Repository Dsm-DAS/DAS_BACKEND, pull requests merged in 2022-12, with the labels that each got.

#120 🔀 :: (#119) 모집글 작성 API 수정
  .github/CODEOWNERS
  src/main/java/com/das/das_backend/domain/feed/domain/Feed.java
  src/main/java/com/das/das_backend/domain/feed/presentation/dto/request/CreateFeedRequest.java
  src/main/java/com/das/das_backend/domain/feed/service/CreateFeedService.java
  src/main/java/com/das/das_backend/domain/user/presentation/dto/response/QueryMyInfoResponse.java
  src/main/java/com/das/das_backend/domain/user/service/QueryMyInfoService.java
Labels: 기능 수정

#122 🔀 :: (#121) 좋아요 연관관계 수정
  src/main/java/com/das/das_backend/domain/club/domain/Club.java
  src/main/java/com/das/das_backend/domain/club/domain/repository/ClubRepository.java
  src/main/java/com/das/das_backend/domain/club/exception/.gitkeep
  src/main/java/com/das/das_backend/domain/club/exception/ClubNotFoundException.java
  src/main/java/com/das/das_backend/domain/club/facade/.gitkeep
  src/main/java/com/das/das_backend/domain/club/facade/ClubFacade.java
  src/main/java/com/das/das_backend/domain/feed/domain/Feed.java
  src/main/java/com/das/das_backend/domain/feed/presentation/dto/response/QueryFeedDetailResponse.java
  src/main/java/com/das/das_backend/domain/feed/presentation/dto/response/QueryFeedListResponse.java
  src/main/java/com/das/das_backend/domain/feed/service/CreateFeedService.java
  src/main/java/com/das/das_backend/domain/feed/service/QueryFeedDetailService.java
  src/main/java/com/das/das_backend/domain/feed/service/QueryFeedListService.java
  src/main/java/com/das/das_backend/domain/feed/service/QueryFeedListViewsService.java
  src/main/java/com/das/das_backend/domain/like/domain/Like.java
  src/main/java/com/das/das_backend/domain/like/domain/repository/LikeRepository.java
  src/main/java/com/das/das_backend/domain/like/facade/LikeFacade.java
  src/main/java/com/das/das_backend/domain/like/service/LikeService.java
  src/main/java/com/das/das_backend/global/error/ErrorCode.java
Labels: 기능 수정

#124 🔀 :: (#123) 모집글 수정 API 변경
  src/main/java/com/das/das_backend/domain/feed/domain/Feed.java
  src/main/java/com/das/das_backend/domain/feed/presentation/dto/request/UpdateFeedRequest.java
  src/main/java/com/das/das_backend/domain/feed/service/UpdateFeedService.java
Labels: 기능 수정

#128 🔀 :: (#127) 유저 리스트 전체 조회 추가
  src/main/java/com/das/das_backend/domain/user/domain/repository/UserRepository.java
  src/main/java/com/das/das_backend/domain/user/presentation/UserController.java
  src/main/java/com/das/das_backend/domain/user/presentation/dto/response/QueryUserListResponse.java
  src/main/java/com/das/das_backend/domain/user/service/QueryUserListService.java
Labels: 기능 추가

#144 🔀 :: (#143) CD 오류 수정
  .github/workflows/CD.yml
  Dockerfile
  build.gradle
Labels: 버그

#151 🔀 :: (#145) Club 수정 추가
  src/main/java/com/das/das_backend/domain/club/domain/Club.java
  src/main/java/com/das/das_backend/domain/club/presentation/ClubController.java
  src/main/java/com/das/das_backend/domain/club/presentation/dto/request/UpdateClubRequest.java
  src/main/java/com/das/das_backend/domain/club/service/UpdateClubService.java
Labels: 기능 추가

#152 🔀 :: (#146) Club 삭제 추가
  src/main/java/com/das/das_backend/domain/club/presentation/ClubController.java
  src/main/java/com/das/das_backend/domain/club/service/DeleteClubService.java
Labels: 기능 추가

#154 🔀 :: (#153) 동아리 리스트 전체 조회 api
  src/main/java/com/das/das_backend/domain/club/domain/repository/ClubRepository.java
  src/main/java/com/das/das_backend/domain/club/presentation/ClubController.java
  src/main/java/com/das/das_backend/domain/club/presentation/dto/response/QueryClubElement.java
  src/main/java/com/das/das_backend/domain/club/presentation/dto/response/QueryClubListResponse.java
  src/main/java/com/das/das_backend/domain/club/service/QueryClubListService.java
Labels: 기능 추가

#156 🔀 :: (#155) 동아리 상세보기 api
  src/main/java/com/das/das_backend/domain/club/presentation/ClubController.java
  src/main/java/com/das/das_backend/domain/club/presentation/dto/response/QueryClubDetailResponse.java
  src/main/java/com/das/das_backend/domain/club/service/QueryClubDetailService.java
  src/main/java/com/das/das_backend/domain/user/facade/UserFacade.java
  src/main/java/com/das/das_backend/domain/user/presentation/dto/response/QueryUserElement.java
Labels: 기능 추가
